name: Build

on:
  push:
    branches: 
      - main
      - dev
      - COS3711-03-01
      - feature/*

  pull_request:
    branches: 
      - main
      - dev
      - COS3711-03-01

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev qt6-base-dev qt6-tools-dev qt6-tools-dev-tools cmake g++

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ../COS3711-03-01/
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
          
    outputs:
      build-success: ${{ steps.build.outcome == 'success' }}
