name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test:
    needs: Build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev qt6-base-dev qt6-tools-dev qt6-tools-dev-tools cmake g++

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Build and run unit tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Build and run integration tests
        run: |
          cd build/tests/integration
          ctest --output-on-failure

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/tests/
